Id: int64 
Aspect: int64 
Cover_Type: int64 
Elevation: int64 
Hillshade_3pm: int64 
Hillshade_9am: int64 
Hillshade_Noon: int64
Horizontal_Distance_To_Fire_Points: int64 
Horizontal_Distance_To_Hydrology: int64 
Horizontal_Distance_To_Roadways: int64 
Slope: int64 
Soil_Type1: int64 
Soil_Type10: int64 
Soil_Type11: int64 
Soil_Type12: int64 
Soil_Type13: int64 
Soil_Type14: int64 
Soil_Type15: int64 
Soil_Type16: int64 
Soil_Type17: int64 
Soil_Type18: int64 
Soil_Type19: int64 
Soil_Type2: int64 
Soil_Type20: int64 
Soil_Type21: int64 
Soil_Type22: int64 
Soil_Type23: int64 
Soil_Type24: int64 
Soil_Type25: int64 
Soil_Type26: int64 
Soil_Type27: int64 
Soil_Type28: int64 
Soil_Type29: int64 
Soil_Type3: int64 
Soil_Type30: int64 
Soil_Type31: int64 
Soil_Type32: int64 
Soil_Type33: int64 
Soil_Type34: int64 
Soil_Type35: int64 
Soil_Type36: int64 
Soil_Type37: int64 
Soil_Type38: int64 
Soil_Type39: int64 
Soil_Type4: int64 
Soil_Type40: int64 
Soil_Type5: int64 
Soil_Type6: int64 
Soil_Type7: int64 
Soil_Type8: int64 
Soil_Type9: int64 
Vertical_Distance_To_Hydrology: int64 
Wilderness_Area1: int64 
Wilderness_Area2: int64 
Wilderness_Area3: int64 
Wilderness_Area4: int64